#!/usr/bin/env python3
"""Emit the Glu instance-class stub for the LuaLS library.

The library formatter emits one stub per source file, each declaring a named
`---@class XxxClass` (a local, never a global). None of them describe the object
a consumer actually holds: the value returned by
`require("<pkg>/vendor/Glu-single")(pkg)`, which carries every glass module as a
field (`glu.table`, `glu.string`, ...).

This script reads the glass registrations in the source (`name = "table"`,
`class_name = "TableClass"`) -- the authoritative field->class mapping -- keeps
the ones whose class actually has a generated stub, and writes
`glu_instance.lua` declaring `---@class Glu` with one `@field` per module.
Consumers then type their local against it:

    ---@type Glu
    local glu = require("MyPkg/vendor/Glu-single")("MyPkg")

Run after the library is built (see `npm run build:lib`):

    python gen-library-instance.py src/scripts build/library
"""
import re
import argparse
from pathlib import Path

OUTPUT_NAME = "glu_instance.lua"

# The factory itself is not a field on its own instances.
SKIP_NAMES = {"glu_glass", "glu"}

NAME_RE = re.compile(r'\bname\s*=\s*"([a-z_][\w]*)"')
CLASS_NAME_RE = re.compile(r'\bclass_name\s*=\s*"([A-Za-z_][\w]*)"')
LIB_CLASS_RE = re.compile(r'^---@class\s+([A-Za-z_][\w]*)', re.MULTILINE)


def stub_classes(library_dir):
    """Return the set of @class names that have a generated stub."""
    classes = set()

    for path in library_dir.glob("*.lua"):
        if path.name == OUTPUT_NAME:
            continue

        for match in LIB_CLASS_RE.finditer(path.read_text(encoding="utf-8")):
            classes.add(match.group(1))

    return classes


def collect(source_dir, library_dir):
    """Pair each glass's field name with its class, keeping only stubbed ones."""
    available = stub_classes(library_dir)
    pairs = []

    for path in sorted(source_dir.glob("*.lua")):
        text = path.read_text(encoding="utf-8")
        name = NAME_RE.search(text)
        class_name = CLASS_NAME_RE.search(text)

        if not name or not class_name:
            continue

        field, cls = name.group(1), class_name.group(1)

        if field in SKIP_NAMES or cls not in available:
            continue

        pairs.append((field, cls))

    return sorted(set(pairs))


def render(pairs):
    """Render the LuaLS stub text for the collected pairs."""
    width = max((len(field) for field, _ in pairs), default=0)
    fields = "\n".join(
        f"---@field {field.ljust(width)} {cls}"
        for field, cls in pairs
    )

    return f"""---@meta

------------------------------------------------------------------------------
-- Glu (instance shape) -- GENERATED by gen-library-instance.py, do not edit.
--
-- Describes the object returned by `require("<pkg>/vendor/Glu-single")(pkg)`.
-- Each glass module is attached to the instance under its registered name,
-- so consumers reach them as `glu.table`, `glu.string`, etc.
--
--   ---@type Glu
--   local glu = require("MyPkg/vendor/Glu-single")("MyPkg")
------------------------------------------------------------------------------

---@class Glu
{fields}
"""


def main():
    parser = argparse.ArgumentParser(
        description="Generate the Glu instance-class stub for the LuaLS library")
    parser.add_argument("source_dir", help="Directory of glass source scripts")
    parser.add_argument("library_dir", help="Directory of generated library stubs")
    args = parser.parse_args()

    source_dir = Path(args.source_dir)
    library_dir = Path(args.library_dir)

    for label, path in (("Source", source_dir), ("Library", library_dir)):
        if not path.is_dir():
            raise SystemExit(f"{label} directory not found: {path}")

    pairs = collect(source_dir, library_dir)

    if not pairs:
        raise SystemExit(f"No glass registrations found in {source_dir}")

    output = library_dir / OUTPUT_NAME
    output.write_text(render(pairs), encoding="utf-8")

    print(f"Wrote {output} ({len(pairs)} modules)")


if __name__ == "__main__":
    main()
