describe("date module", function()
  local g

  setup(function()
    g = Glu("Glu")
  end)

  describe("shms", function()
    it("should return hours, minutes, seconds for 350 seconds", function()
      local h, m, s = g.date.shms(350)
      assert.are.equal("00", h)
      assert.are.equal("05", m)
      assert.are.equal("50", s)
    end)

    it("should return all zeros for 0 seconds", function()
      local h, m, s = g.date.shms(0)
      assert.are.equal("00", h)
      assert.are.equal("00", m)
      assert.are.equal("00", s)
    end)

    it("should handle negative seconds", function()
      local h, m, s = g.date.shms(-350)
      assert.are.equal("23", h)
      assert.are.equal("54", m)
      assert.are.equal("10", s)
    end)

    it("should return a string when as_string is true", function()
      local result = g.date.shms(350, true)
      assert.are.equal("5m 50s", result)
    end)

    it("should handle large values", function()
      local h, m, s = g.date.shms(86399)
      assert.are.equal("23", h)
      assert.are.equal("59", m)
      assert.are.equal("59", s)
    end)

    it("should handle exactly one hour", function()
      local h, m, s = g.date.shms(3600)
      assert.are.equal("01", h)
      assert.are.equal("00", m)
      assert.are.equal("00", s)
    end)

    it("should include hours in string output when applicable", function()
      local result = g.date.shms(3661, true)
      assert.are.equal("1h 1m 1s", result)
    end)

    it("should handle fractional seconds", function()
      local h, m, s = g.date.shms(350.7)
      assert.are.equal("00", h)
      assert.are.equal("05", m)
      assert.are.equal("50", s)
    end)

    it("should return empty string for 0 seconds in string mode", function()
      local result = g.date.shms(0, true)
      assert.are.equal("", result)
    end)

    it("should handle exactly one minute", function()
      local h, m, s = g.date.shms(60)
      assert.are.equal("00", h)
      assert.are.equal("01", m)
      assert.are.equal("00", s)
    end)

    it("should handle exactly one minute in string mode", function()
      local result = g.date.shms(60, true)
      assert.are.equal("1m", result)
    end)

    it("should handle seconds only in string mode", function()
      local result = g.date.shms(45, true)
      assert.are.equal("45s", result)
    end)

    it("should handle hours only in string mode", function()
      local result = g.date.shms(7200, true)
      assert.are.equal("2h", result)
    end)

    it("should error when first argument is not a number", function()
      assert.has_error(function()
        g.date.shms("hello")
      end)
    end)

    it("should error when second argument is not a boolean", function()
      assert.has_error(function()
        g.date.shms(100, "yes")
      end)
    end)

    it("should accept nil for second argument", function()
      assert.has_no.errors(function()
        g.date.shms(100, nil)
      end)
    end)
  end)
end)
